## tidb version
# "tidb.version" = "v4.0.12" # other values: nightly

## general
# host = ""
# monitor = false

## db
# db = 1
# "db.binpath" = "current" # current means to use the current repo binary, will fallback to default binary if it doesn't exist
# "db.config" = "components-config/tidb.config"
# "db.host" = ""

## kv
# kv = 1
# "kv.binpath" = "current"
# "kv.config" = "components-config/tikv.config"

## pd
# pd = 1
# "pd.binpath" = "current"
# "pd.config" = "components-config/pd.config"
# "pd.host" = ""

## tiflash
# tiflash = 0 # set to 0 to not deploy it
# "tiflash.binpath" = ""
# "tiflash.config" = "components-config/tiflash.config"

## drainer
# drainer = 0
# "drainer.binpath" = ""
# "drainer.config" = ""

## pump
# pump = 0
# "pump.binpath" = ""
# "pump.config" = ""

## ticdc
# ticdc = 0
# "ticdc.binpath" = ""
